version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
  php:
    build:
      context: ./php
    ports:
      - '9000:9000'
      - '80:80'
    volumes:
      - ./../:/var/www/app/
    command: sh -c "php -S 172.18.0.3:80"
    depends_on:
      - mysql